---
# tasks file for vmware-restore-snapshot
- name: Restore snapshot
  community.vmware.vmware_guest_snapshot:
    validate_certs: no
    datacenter: "{{ vm_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ inventory_hostname }}"
    state: revert
    snapshot_name: ansible_managed_snapshot_{{ inventory_hostname }}
  connection: local
  delegate_to: localhost
  become: false

- name: Wait for the virtual machine to start back up after restore
  community.vmware.vmware_guest_powerstate:    
    name: "{{ inventory_hostname }}"
    state: powered-on
    state_change_timeout: 360
  connection: local
  delegate_to: localhost