---
# tasks file for vmware-delete-snapshot
- name: Delete snapshot
  community.vmware.vmware_guest_snapshot:
    validate_certs: no
    datacenter: "{{ vm_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ inventory_hostname }}"
    state: absent
    snapshot_name: ansible_managed_snapshot_{{ inventory_hostname }}
  connection: local
  delegate_to: localhost
  become: false
